import { expect, test } from "./helpers/test";
import { getEditorState, gotoEditor } from "./helpers/e2e";

// Minimal figure shapes for loadTestProject. Extra fields (name/moldMeta) are
// spread through verbatim by the editor's loadProject.
type TestNode = { id: string; x: number; y: number; mode: "corner" };
type TestFigure = {
  id: string;
  tool: "line";
  kind?: "mold";
  name?: string;
  x: number;
  y: number;
  rotation: number;
  closed: boolean;
  nodes: TestNode[];
  edges: Array<{ id: string; from: string; to: string; kind: "line" }>;
  stroke: string;
  strokeWidth: number;
  fill: string;
  opacity: number;
  nameFontSizePx?: number;
  nameRotationDeg?: number;
  moldMeta?: {
    baseSize?: string;
    cutQuantity?: number;
    cutOnFold?: boolean;
    notes?: string;
    docFontSizePx?: number;
    visible?: boolean;
    printEnabled?: boolean;
    grainline?: { angleDeg: number; autoGenerated?: boolean };
  };
};

type FigureSnapshot = {
  id: string;
  kind?: string;
  name?: string;
  x?: number;
  y?: number;
  nameFontSizePx?: number;
  nameRotationDeg?: number;
  nameOffsetLocal?: { x: number; y: number };
  moldMeta?: {
    baseSize?: string;
    cutQuantity?: number;
    cutOnFold?: boolean;
    notes?: string;
    docFontSizePx?: number;
    grainline?: { angleDeg: number };
    grainOffsetLocal?: { x: number; y: number };
  };
};

/** Closed rectangle. World coords == screen coords in a fresh editor. */
function createRect(
  id: string,
  x: number,
  y: number,
  w: number,
  h: number,
  extra?: Partial<TestFigure>
): TestFigure {
  const a = `${id}_a`;
  const b = `${id}_b`;
  const c = `${id}_c`;
  const d = `${id}_d`;
  return {
    id,
    tool: "line",
    x: 0,
    y: 0,
    rotation: 0,
    closed: true,
    nodes: [
      { id: a, x, y, mode: "corner" },
      { id: b, x: x + w, y, mode: "corner" },
      { id: c, x: x + w, y: y + h, mode: "corner" },
      { id: d, x, y: y + h, mode: "corner" },
    ],
    edges: [
      { id: `${id}_e1`, from: a, to: b, kind: "line" },
      { id: `${id}_e2`, from: b, to: c, kind: "line" },
      { id: `${id}_e3`, from: c, to: d, kind: "line" },
      { id: `${id}_e4`, from: d, to: a, kind: "line" },
    ],
    stroke: "aci7",
    strokeWidth: 2,
    fill: "rgba(96,165,250,0.22)",
    opacity: 1,
    ...extra,
  };
}

async function loadFigures(
  page: import("@playwright/test").Page,
  figures: TestFigure[]
) {
  await page.evaluate((payload) => {
    window.__INAA_DEBUG__?.loadTestProject?.({ figures: payload });
  }, figures);
  await expect
    .poll(async () =>
      page.evaluate(() => window.__INAA_DEBUG__?.getState?.().figuresCount ?? 0)
    )
    .toBe(figures.length);
}

async function getFigures(
  page: import("@playwright/test").Page
): Promise<FigureSnapshot[]> {
  return page.evaluate(
    () =>
      (window.__INAA_DEBUG__?.getFiguresSnapshot?.() ?? []) as FigureSnapshot[]
  );
}

async function selectAt(
  page: import("@playwright/test").Page,
  x: number,
  y: number
) {
  const stage = page.getByTestId("editor-stage-container");
  await expect(stage).toBeVisible();
  await stage.click({ position: { x, y } });
  await expect
    .poll(async () => (await getEditorState(page)).selectedFigureId)
    .not.toBeNull();
}

async function countByName(
  page: import("@playwright/test").Page,
  name: string
): Promise<number> {
  return page.evaluate(
    (n) => window.__INAA_DEBUG__?.countStageNodesByName?.(n) ?? 0,
    name
  );
}

// A tall rect mold centered at (300, 280).
function moldRect(id: string, extra?: Partial<TestFigure>): TestFigure {
  return createRect(id, 220, 180, 160, 200, { kind: "mold", ...extra });
}
const MOLD_CX = 300;
const MOLD_CY = 280;

test("conversão de figura em molde copia o nome existente", async ({
  page,
}) => {
  await gotoEditor(page);
  const stage = page.getByTestId("editor-stage-container");
  await expect(stage).toBeVisible();

  await loadFigures(page, [
    createRect("fig_named", 200, 200, 140, 100, { name: "Frente" }),
  ]);

  await stage.click({ button: "right", position: { x: 260, y: 250 } });
  await expect(page.getByTestId("edge-context-menu")).toBeVisible();
  await page.getByTestId("edge-context-convert-figure-to-mold").click();
  await expect(page.getByTestId("edge-context-menu")).toHaveCount(0);

  await expect
    .poll(async () => {
      const f = (await getFigures(page))[0];
      return f ? `${f.kind}:${f.name}` : null;
    })
    .toBe("mold:Frente");
});

test("conversão de figura sem nome recebe nome padrão Molde N", async ({
  page,
}) => {
  await gotoEditor(page);
  const stage = page.getByTestId("editor-stage-container");
  await expect(stage).toBeVisible();

  await loadFigures(page, [createRect("fig_unnamed", 200, 200, 140, 100)]);

  await stage.click({ button: "right", position: { x: 260, y: 250 } });
  await expect(page.getByTestId("edge-context-menu")).toBeVisible();
  await page.getByTestId("edge-context-convert-figure-to-mold").click();
  await expect(page.getByTestId("edge-context-menu")).toHaveCount(0);

  await expect
    .poll(async () => (await getFigures(page))[0]?.name ?? null)
    .toMatch(/^Molde \d+$/);
});

test("painel do molde consolida documentação e oculta 'Nome da figura'", async ({
  page,
}) => {
  await gotoEditor(page);
  await loadFigures(page, [moldRect("mold_panel", { name: "Frente" })]);
  await selectAt(page, MOLD_CX, MOLD_CY);

  // Consolidated section + all fields present.
  await expect(
    page.getByRole("button", { name: "Documentação do molde" })
  ).toBeVisible();
  await expect(page.getByTestId("mold-name-input")).toBeVisible();
  await expect(page.getByTestId("mold-name-font-size")).toBeVisible();
  await expect(page.getByTestId("mold-base-size")).toBeVisible();
  await expect(page.getByTestId("mold-quantity")).toBeVisible();
  await expect(page.getByTestId("mold-cut-on-fold")).toBeVisible();
  await expect(page.getByTestId("mold-grainline-enabled")).toBeVisible();
  await expect(page.getByTestId("mold-notes")).toBeVisible();
  await expect(page.getByTestId("mold-doc-font-size")).toBeVisible();
  // Rotation moved to the inner transform mode (double-click on a handle) —
  // there is no panel control anymore.
  await expect(page.getByTestId("mold-doc-rotate")).toHaveCount(0);

  // The standalone "Nome da figura" section must NOT be shown for molds.
  await expect(
    page.getByRole("button", { name: "Nome da figura" })
  ).toHaveCount(0);
});

test("figura comum mantém seção 'Nome da figura' (sem documentação de molde)", async ({
  page,
}) => {
  await gotoEditor(page);
  await loadFigures(page, [
    createRect("plain_fig", 220, 180, 160, 200, { name: "Costas" }),
  ]);
  await selectAt(page, MOLD_CX, MOLD_CY);

  await expect(
    page.getByRole("button", { name: "Nome da figura" })
  ).toBeVisible();
  await expect(page.getByTestId("mold-name-input")).toHaveCount(0);
  await expect(
    page.getByRole("button", { name: "Documentação do molde" })
  ).toHaveCount(0);
});

test("documentação preenchida é desenhada no molde (linhas + sem seta quando fio vazio)", async ({
  page,
}) => {
  await gotoEditor(page);
  await loadFigures(page, [
    moldRect("mold_doc", {
      name: "Frente",
      moldMeta: {
        baseSize: "M",
        cutQuantity: 2,
        cutOnFold: true,
        visible: true,
        printEnabled: true,
      },
    }),
  ]);
  await selectAt(page, MOLD_CX, MOLD_CY);

  // name + Tam + Qtd + Cortar na dobra = 4 lines, no grain arrow yet.
  await expect.poll(() => countByName(page, "inaa-mold-doc-line")).toBe(4);
  await expect.poll(() => countByName(page, "inaa-mold-grainline")).toBe(0);
});

test("fio: seletor Sim/Não liga e desliga a seta", async ({ page }) => {
  await gotoEditor(page);
  await loadFigures(page, [moldRect("mold_fio", { name: "Frente" })]);
  await selectAt(page, MOLD_CX, MOLD_CY);

  const fio = page.getByTestId("mold-grainline-enabled");
  await expect(fio).toHaveValue("nao");
  await expect.poll(() => countByName(page, "inaa-mold-grainline")).toBe(0);

  // Sim → arrow appears. The mold is taller than wide, so the auto heuristic
  // picks 90°.
  await fio.selectOption("sim");
  await expect.poll(() => countByName(page, "inaa-mold-grainline")).toBe(1);
  await expect
    .poll(async () => (await getFigures(page))[0]?.moldMeta?.grainline?.angleDeg)
    .toBe(90);

  // Não → arrow gone, grainline cleared.
  await fio.selectOption("nao");
  await expect.poll(() => countByName(page, "inaa-mold-grainline")).toBe(0);
  await expect
    .poll(async () => (await getFigures(page))[0]?.moldMeta?.grainline ?? null)
    .toBeNull();
});

test("girar os textos (transform interno) não move a seta do fio", async ({
  page,
}) => {
  await gotoEditor(page);
  await loadFigures(page, [
    moldRect("mold_rot", {
      name: "Frente",
      moldMeta: { grainline: { angleDeg: 30 } },
    }),
  ]);
  await selectAt(page, MOLD_CX, MOLD_CY);

  await expect.poll(() => countByName(page, "inaa-mold-grainline")).toBe(1);
  const grainBefore = await page.evaluate(
    () =>
      window.__INAA_DEBUG__?.getStageNodePointsByName?.("inaa-mold-grainline") ??
      []
  );

  // Enter the doc block's inner transform mode and rotate it ~30°.
  const stage = page.getByTestId("editor-stage-container");
  const box = await stage.boundingBox();
  const handles = await page.evaluate(
    () =>
      window.__INAA_DEBUG__?.getStageNodeAbsolutePositionsByName?.(
        "inaa-figure-name-handle"
      ) ?? []
  );
  await page.mouse.dblclick(box!.x + handles[0]!.x, box!.y + handles[0]!.y);
  await expect
    .poll(() => countByName(page, "inaa-inner-proxy-doc"))
    .toBe(1);

  // Poll for the INNER transformer's rotater near the block (right after
  // entering the mode the anchors may not be positioned yet, and the detached
  // outer transformer parks its anchors far away).
  let rotater: { x: number; y: number } | null = null;
  await expect
    .poll(async () => {
      const rects = await page.evaluate(
        () =>
          window.__INAA_DEBUG__?.getStageNodeClientRectsByName?.("rotater") ??
          []
      );
      // Reverse: the inner transformer mounts after the outer one, whose
      // detached anchors keep stale positions that can also fall in range.
      for (const r of [...rects].reverse()) {
        const c = { x: r.x + r.width / 2, y: r.y + r.height / 2 };
        if (Math.hypot(c.x - MOLD_CX, c.y - MOLD_CY) <= 200) {
          rotater = c;
          return true;
        }
      }
      return false;
    })
    .toBe(true);
  const start = {
    x: box!.x + rotater!.x,
    y: box!.y + rotater!.y,
  };
  const pivot = { x: box!.x + MOLD_CX, y: box!.y + MOLD_CY };
  const rad = (30 * Math.PI) / 180;
  const end = {
    x: pivot.x + (start.x - pivot.x) * Math.cos(rad) - (start.y - pivot.y) * Math.sin(rad),
    y: pivot.y + (start.x - pivot.x) * Math.sin(rad) + (start.y - pivot.y) * Math.cos(rad),
  };
  await page.mouse.move(start.x, start.y);
  await page.mouse.down();
  await page.mouse.move(end.x, end.y, { steps: 8 });
  await page.mouse.up();

  await expect
    .poll(async () => Math.abs(((await getFigures(page))[0]?.nameRotationDeg ?? 0) - 30))
    .toBeLessThan(8);

  // Grain arrow direction is driven by the fio value, not the text rotation.
  const grainAfter = await page.evaluate(
    () =>
      window.__INAA_DEBUG__?.getStageNodePointsByName?.("inaa-mold-grainline") ??
      []
  );
  expect(JSON.stringify(grainAfter)).toBe(JSON.stringify(grainBefore));
});

test("a seta do fio não sobrepõe o bloco de documentação", async ({ page }) => {
  await gotoEditor(page);
  await loadFigures(page, [
    moldRect("mold_no_overlap", {
      name: "Frente",
      moldMeta: {
        baseSize: "M",
        cutQuantity: 2,
        cutOnFold: true,
        grainline: { angleDeg: 30 },
      },
    }),
  ]);
  await selectAt(page, MOLD_CX, MOLD_CY);

  await expect.poll(() => countByName(page, "inaa-mold-doc-line")).toBe(4);
  await expect.poll(() => countByName(page, "inaa-mold-grainline")).toBe(1);

  const rects = await page.evaluate(() => {
    const get = (n: string) =>
      window.__INAA_DEBUG__?.getStageNodeClientRectsByName?.(n) ?? [];
    return {
      doc: get("inaa-mold-doc"),
      arrow: [
        ...get("inaa-mold-grainline"),
        ...get("inaa-mold-grainline-head"),
      ],
    };
  });
  expect(rects.doc).toHaveLength(1);
  expect(rects.arrow).toHaveLength(2);

  const doc = rects.doc[0]!;
  for (const r of rects.arrow) {
    const separated =
      r.x + r.width <= doc.x ||
      doc.x + doc.width <= r.x ||
      r.y + r.height <= doc.y ||
      doc.y + doc.height <= r.y;
    expect(separated).toBe(true);
  }
});

test("arrastar o handle move o bloco de documentação sem mover o molde", async ({
  page,
}) => {
  await gotoEditor(page);
  await loadFigures(page, [moldRect("mold_handle", { name: "Frente" })]);
  await selectAt(page, MOLD_CX, MOLD_CY);

  await expect
    .poll(() => countByName(page, "inaa-figure-name-handle"))
    .toBe(1);

  const positions = await page.evaluate(
    () =>
      window.__INAA_DEBUG__?.getStageNodeAbsolutePositionsByName?.(
        "inaa-figure-name-handle"
      ) ?? []
  );
  expect(positions).toHaveLength(1);

  const stage = page.getByTestId("editor-stage-container");
  const box = await stage.boundingBox();
  expect(box).not.toBeNull();
  // The handle rect is center-anchored (x/y + offset), so its absolute
  // position IS its visual center — aim straight at it.
  const startX = box!.x + positions[0]!.x;
  const startY = box!.y + positions[0]!.y;

  await page.mouse.move(startX, startY);
  await page.mouse.down();
  await page.mouse.move(startX + 40, startY + 30, { steps: 5 });
  await page.mouse.up();

  const fig = (await getFigures(page))[0]!;
  // The documentation block followed the pointer...
  expect(Math.abs((fig.nameOffsetLocal?.x ?? 0) - 40)).toBeLessThan(3);
  expect(Math.abs((fig.nameOffsetLocal?.y ?? 0) - 30)).toBeLessThan(3);
  // ...and the mold itself stayed put (regression: stage direct-drag used to
  // move the figure together with the handle).
  expect(fig.x ?? 0).toBe(0);
  expect(fig.y ?? 0).toBe(0);
});

test("a seta do fio tem handle próprio que move só a seta", async ({
  page,
}) => {
  await gotoEditor(page);
  await loadFigures(page, [
    moldRect("mold_grain_drag", {
      name: "Frente",
      moldMeta: { grainline: { angleDeg: 0 } },
    }),
  ]);
  await selectAt(page, MOLD_CX, MOLD_CY);

  await expect.poll(() => countByName(page, "inaa-grain-handle")).toBe(1);
  await expect
    .poll(() => countByName(page, "inaa-figure-name-handle"))
    .toBe(1);

  const grainPointsBefore = await page.evaluate(
    () =>
      window.__INAA_DEBUG__?.getStageNodePointsByName?.(
        "inaa-mold-grainline"
      )?.[0] ?? []
  );
  expect(grainPointsBefore.length).toBe(4);

  // Drag the grain handle by (+60, +50). The handle rect is center-anchored,
  // so its absolute position is its visual center.
  const positions = await page.evaluate(
    () =>
      window.__INAA_DEBUG__?.getStageNodeAbsolutePositionsByName?.(
        "inaa-grain-handle"
      ) ?? []
  );
  expect(positions).toHaveLength(1);
  const stage = page.getByTestId("editor-stage-container");
  const box = await stage.boundingBox();
  const startX = box!.x + positions[0]!.x;
  const startY = box!.y + positions[0]!.y;
  await page.mouse.move(startX, startY);
  await page.mouse.down();
  await page.mouse.move(startX + 60, startY + 50, { steps: 5 });
  await page.mouse.up();

  // The arrow moved by the drag delta…
  const grainPointsAfter = await page.evaluate(
    () =>
      window.__INAA_DEBUG__?.getStageNodePointsByName?.(
        "inaa-mold-grainline"
      )?.[0] ?? []
  );
  expect(grainPointsAfter.length).toBe(4);
  for (let i = 0; i < 4; i += 2) {
    expect(Math.abs(grainPointsAfter[i]! - grainPointsBefore[i]! - 60)).toBeLessThan(3);
    expect(
      Math.abs(grainPointsAfter[i + 1]! - grainPointsBefore[i + 1]! - 50)
    ).toBeLessThan(3);
  }

  // …the offset persisted, and neither the mold nor the text block moved.
  const fig = (await getFigures(page))[0]!;
  expect(Number.isFinite(fig.moldMeta?.grainOffsetLocal?.x ?? NaN)).toBe(true);
  expect(Number.isFinite(fig.moldMeta?.grainOffsetLocal?.y ?? NaN)).toBe(true);
  expect((fig as { x?: number }).x ?? 0).toBe(0);
  expect((fig as { y?: number }).y ?? 0).toBe(0);
  expect(fig.nameOffsetLocal ?? { x: 0, y: 0 }).toEqual({ x: 0, y: 0 });
});

test("tamanho do nome e tamanho do texto são independentes", async ({
  page,
}) => {
  await gotoEditor(page);
  await loadFigures(page, [moldRect("mold_fonts", { name: "Frente" })]);
  await selectAt(page, MOLD_CX, MOLD_CY);

  await page.getByTestId("mold-doc-font-size").selectOption("32");
  await page.getByTestId("mold-name-font-size").selectOption("48");

  await expect
    .poll(async () => {
      const f = (await getFigures(page))[0];
      return `${f?.moldMeta?.docFontSizePx}:${f?.nameFontSizePx}`;
    })
    .toBe("32:48");
});
